### ISSUE TITLE
Non functioning video (Gstreamer) using a cheap nixos build.

### ISSUE THREAD

**Issue by bqv** [akirakyle/emacs-webkit#13]
I appreciate this isn't on melpa yet so I'm currently using a dirty build thusly: https://github.com/bqv/nixrc/blob/9b83b653beece696197ccc9219a48f57692eea60/pkgs/applications/editors/emacs-modes/default.nix#L62-L91

Since this is a dynamic module, it can't quite easily be wrapped on nixos to work properly with gstreamer. Would you consider some avenue for mitigating this, or is your plan to just require emacs to be wrapped as a whole for it to work?

(I note you're a nix user, so I'm crossing my fingers...)

**Comment by bqv** [comment]
P.S. happy to contribute a nix package if you're not planning on touching melpa for some time

**Comment by akirakyle** [comment]
I haven't had the chance to really look into this so thanks for checking it out. I don't really have a plan for the best way for this to be packaged on any system really. Also while I use nix for my system, I still use straight to manage my Emacs packages since I appreciate how easy it makes to contribute given everything is already pulled in from git, but I have considered moving to a hybrid approach...

That said my focus right now isn't going to be on packaging, but I really appreciate the contributions!

**Comment by bqv** [comment]
FYI fixed by adding to the env at emacs runtime before require-ing this package: https://github.com/bqv/nixrc/blob/8734eee98942a0af5f77b6d7c20d7344c0afa5bb/emacs/webkit.nix#L25-L28

Edit: Nevermind, not sure that fixed it...

**Comment by bqv** [comment]
Had time to check this deeper. Issue was that I needed to do the gstreamer and gapps wrapping to emacs itself, not the module. Works now :)
