### ISSUE TITLE
xwidget-webkit no longer work with latest webkit2gtk library, would you consider maintaining this project again?

### ISSUE THREAD

**Issue by BooAA** [akirakyle/emacs-webkit#44]
Hi, I saw the README recommend the built-in `xwidget-webkit`, but since `webkitgtk 2.41` offscreen rendering no longer work, which make `xwidget-webkit` crash in Emacs (discussion in [bug#66068: 30.0.50; xwidget-webkit-browse-url makes Emacs abort](https://mail.gnu.org/archive/html/bug-gnu-emacs/2023-09/msg02680.html)). Po Lu has recommended shipping to WPE but looks like the emacs-dev has no interest to it. Would you consider pick up this `emacs-webkit` project again as `xwidget-webkit` is very likely to be broken/deprecated in the future? (on debian unstable,` xwidget-webkit` have already been  broken for several months and I don't think the webkit-dev is going to fix this in the future).

Thanks.

**Comment by akirakyle** [comment]
Thanks for letting me know about that issue. I sort of figured this day would come sooner or later back when I was writing emacs-webkit which is why I decided not to implement the offscreen rendering hack to have multiple webkit views in emacs. I think the recommendation to switch to WPE dramatically underestimates just how difficult that would be since, in my understanding, WPE leaves a lot more up to the application to implement and while it's probably technically capable of allowing emacs to have multiple webkit views, I wouldn't guess this is a main use case supported by WPE.

Unfortunately it's still the case that I don't have either the time or interest to start working on emacs-webkit again. Although I should say I am still very much interested in figuring out ways to integrate emacs and a web browser. I do continue to spend some free time here and there hacking on various ideas I have about how to accomplish that in less fundamentally hacky ways than emacs-webkit. So perhaps one day I might have something worthwhile as a successor to emacs-webkit.

**Comment by irisjae** [comment]
In case it's of any interest, 1) recently, webkit offscreen rendering should be working again (https://github.com/emacs-mirror/emacs/commit/4e855f90d1b1c3996b408d3f5d9e02d0ca7fd792) (https://discourse.nixos.org/t/emacs-xwidgets-is-not-broken-anymore/77145), 2) another emacs graphical browser, embr.el, was created (via chromium) (this was written on Emacs)
